

import type { Promotion, SalesData, Product, OrganizationHierarchy, ProductHierarchy, Order, OrganizationGroup, SentNotification, Budget, ExternalFactor } from '@/types';

export const salesData: SalesData[] = [
  { month: "Jan '24", sales: 2890 },
  { month: "Feb '24", sales: 2756 },
  { month: "Mar '24", sales: 3322 },
  { month: "Apr '24", sales: 3470 },
  { month: "May '24", sales: 3123 },
  { month: "Jun '24", sales: 3890 },
  { month: "Jul '24", sales: 3590 },
  { month: "Aug '24", sales: 4102 },
];

export const products: Product[] = [
    { id: 'PROD-001', name: 'Cool Cola 300ml', sku: 'CC300', price: 20 },
    { id: 'PROD-002', name: 'Cool Cola 500ml', sku: 'CC500', price: 35 },
    { id: 'PROD-003', name: 'Zesty Orange 300ml', sku: 'ZO300', price: 22 },
    { id: 'PROD-004', name: 'Zesty Orange 500ml', sku: 'ZO500', price: 38 },
    { id: 'PROD-005', name: 'Lemon-Lime Burst 300ml', sku: 'LLB300', price: 21 },
];

export const productHierarchy: ProductHierarchy[] = [
  { id: 'CAT-1', name: 'Beverages', level: 'Category' },
  { id: 'BRAND-1', name: 'Cool Cola', level: 'Brand', parentId: 'CAT-1' },
  { id: 'SKU-1', name: 'Cool Cola 300ml', level: 'SKU', parentId: 'BRAND-1' },
  { id: 'SKU-2', name: 'Cool Cola 500ml', level: 'SKU', parentId: 'BRAND-1' },
  { id: 'BRAND-2', name: 'Zesty Orange', level: 'Brand', parentId: 'CAT-1' },
  { id: 'SKU-3', name: 'Zesty Orange 300ml', level: 'SKU', parentId: 'BRAND-2' },
  { id: 'SKU-4', name: 'Zesty Orange 500ml', level: 'SKU', parentId: 'BRAND-2' },
  { id: 'CAT-2', name: 'Snacks', level: 'Category' },
];

export const organizationHierarchy: OrganizationHierarchy[] = [
    { id: 'HIER-R1', name: 'North', level: 'Region' },
    { id: 'HIER-S1', name: 'Delhi NCR', level: 'State', parentId: 'HIER-R1' },
    { id: 'HIER-A1', name: 'North Delhi', level: 'Area', parentId: 'HIER-S1' },
    { id: 'HIER-D1', name: 'Gupta Distributors', level: 'Distributor', parentId: 'HIER-A1' },
    { id: 'HIER-RET1', name: 'Sharma Kirana Store', level: 'Retailer', parentId: 'HIER-D1' },
    { id: 'HIER-D2', name: 'Modern Traders', level: 'Distributor', parentId: 'HIER-A1' },
    { id: 'HIER-RET2', name: 'City Supermart', level: 'Retailer', parentId: 'HIER-D2' },
    { id: 'HIER-S2', name: 'Punjab', level: 'State', parentId: 'HIER-R1' },
    { id: 'HIER-R2', name: 'West', level: 'Region' },
    { id: 'HIER-S3', name: 'Maharashtra', level: 'State', parentId: 'HIER-R2' },
    { id: 'HIER-D3', name: 'Patel Trading Co.', level: 'Distributor', parentId: 'HIER-S3' },
];

export const organizationGroups: OrganizationGroup[] = [
    { id: 'GROUP-1', name: 'High-Performing Distributors', memberIds: ['HIER-D1', 'HIER-D3'] },
    { id: 'GROUP-2', name: 'New Delhi Retailers', memberIds: ['HIER-RET1', 'HIER-RET2'] },
];


export const promotions: Promotion[] = [
  {
    id: 'PROMO-001',
    schemeName: 'Monsoon Bonanza',
    promotionLevel: 'Secondary',
    status: 'Active',
    startDate: '2024-07-01',
    endDate: '2024-08-31',
    type: 'Quantity-Based Freebie (Buy X, Get Y)',
    uplift: 15.2,
    products: [
        { productId: 'PROD-001', buyQuantity: 6, getQuantity: 1, getProductId: 'PROD-001' }
    ],
    hierarchyIds: ['HIER-R1'],
    productHierarchyIds: ['CAT-1'],
  },
  {
    id: 'PROMO-002',
    schemeName: 'Independence Day Special',
    promotionLevel: 'Secondary',
    status: 'Active',
    startDate: '2024-08-10',
    endDate: '2024-08-20',
    type: 'Bundle',
    uplift: 8.5,
    products: [],
    hierarchyIds: ['HIER-S1'],
    organizationGroupIds: ['GROUP-1'],
    productHierarchyIds: ['BRAND-1'],
    bundleProducts: [
      { productId: 'PROD-002', quantity: 1},
      { productId: 'PROD-004', quantity: 1},
    ],
    bundlePrice: 65,
  },
  {
    id: 'PROMO-003',
    schemeName: 'Diwali Dhamaka',
    promotionLevel: 'Secondary',
    status: 'Upcoming',
    startDate: '2024-10-15',
    endDate: '2024-11-15',
    type: 'Contest',
    uplift: 0,
    products: [],
    hierarchyIds: ['HIER-R1', 'HIER-R2'],
    productHierarchyIds: ['CAT-1', 'CAT-2'],
  },
  {
    id: 'PROMO-004',
    schemeName: 'Summer Cooler Offer',
    promotionLevel: 'Secondary',
    status: 'Expired',
    startDate: '2024-04-01',
    endDate: '2024-05-31',
    type: 'Freebie',
    uplift: 12.5,
    products: [],
    hierarchyIds: ['HIER-S3'],
    productHierarchyIds: ['BRAND-2'],
  },
  {
    id: 'PROMO-005',
    schemeName: 'Holi Hungama',
    promotionLevel: 'Secondary',
    status: 'Expired',
    startDate: '2024-03-10',
    endDate: '2024-03-25',
    type: 'Discount',
    uplift: 22.1,
    products: [],
    hierarchyIds: ['HIER-S1', 'HIER-S2'],
    productHierarchyIds: ['BRAND-1'],
    discountPercentage: 10,
  },
   {
    id: 'PROMO-006',
    schemeName: 'Tiered Volume Push',
    promotionLevel: 'Secondary',
    status: 'Active',
    startDate: '2024-08-01',
    endDate: '2024-09-30',
    type: 'Tiered Volume Discount',
    uplift: 18.0,
    products: [],
    hierarchyIds: ['HIER-R2'],
    productHierarchyIds: ['BRAND-2'],
    discountTiers: [
        { minQuantity: 10, maxQuantity: 49, discountPercentage: 5 },
        { minQuantity: 50, maxQuantity: 99, discountPercentage: 10 },
        { minQuantity: 100, maxQuantity: 9999, discountPercentage: 15 },
    ]
  },
  {
    id: 'PROMO-007',
    schemeName: 'Value-Based Offer',
    promotionLevel: 'Secondary',
    status: 'Upcoming',
    startDate: '2024-09-01',
    endDate: '2024-09-30',
    type: 'Value-Based Discount',
    uplift: 0,
    products: [],
    hierarchyIds: ['HIER-S1'],
    productHierarchyIds: ['BRAND-1'],
    minValue: 5000,
    discountValue: 250,
  },
  {
    id: 'PROMO-008',
    schemeName: 'Must Stock Offer',
    promotionLevel: 'Secondary',
    status: 'Active',
    startDate: '2024-08-15',
    endDate: '2024-09-15',
    type: 'Forced-Buy / Must-Stock',
    uplift: 0,
    products: [],
    hierarchyIds: ['HIER-D1'],
    productHierarchyIds: ['SKU-1'],
    mustBuyProducts: [
      { productId: 'PROD-005', quantity: 5 }
    ],
    discountPercentage: 5,
  },
   {
    id: 'PROMO-009',
    schemeName: 'Q3 Sales Champion',
    promotionLevel: 'Secondary',
    status: 'Active',
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    type: 'QPS (Long-Term Incentive)',
    uplift: 0,
    products: [],
    hierarchyIds: ['HIER-D1'],
    productHierarchyIds: ['BRAND-1'],
    qpsTargetQuantity: 5000,
    qpsDurationMonths: 3,
    qpsReward: 'All-expenses-paid trip to Paris for 2',
  },
  {
    id: 'PROMO-010',
    schemeName: 'Q3 Distributor Bulk Discount',
    promotionLevel: 'Primary',
    status: 'Active',
    startDate: '2024-07-01',
    endDate: '2024-09-30',
    type: 'Discount',
    uplift: 0,
    products: [],
    hierarchyIds: ['HIER-R1', 'HIER-R2'],
    productHierarchyIds: ['CAT-1'],
    discountPercentage: 5,
  },
  {
    id: 'PROMO-011',
    schemeName: 'Annual Growth Rebate',
    promotionLevel: 'Primary',
    status: 'Active',
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    type: 'Rebate and Loyalty Programs',
    uplift: 0,
    products: [],
    hierarchyIds: ['HIER-D1', 'HIER-D2', 'HIER-D3'],
    productHierarchyIds: ['CAT-1', 'CAT-2'],
  },
];

export const orders: Order[] = [
    {
        id: 'ORD-001',
        distributorName: 'Gupta Distributors',
        date: '2024-08-12',
        amount: 45000,
        status: 'Fulfilled',
        appliedPromotionId: 'PROMO-001',
        orderType: 'Retail',
        items: [
            { productId: 'PROD-001', quantity: 200, price: 20 },
            { productId: 'PROD-003', quantity: 100, price: 25 },
        ],
    },
    {
        id: 'ORD-002',
        distributorName: 'Patel Trading Co.',
        date: '2024-08-12',
        amount: 78000,
        status: 'Pending',
        appliedPromotionId: 'PROMO-002',
        orderType: 'Retail',
        items: [
            { productId: 'PROD-002', quantity: 150, price: 35 },
            { productId: 'PROD-004', quantity: 100, price: 35 },
            { productId: 'PROD-005', quantity: 50, price: 22 },
        ],
    },
    {
        id: 'ORD-003',
        distributorName: 'Sharma & Sons',
        date: '2024-08-11',
        amount: 23500,
        status: 'Fulfilled',
        orderType: 'Retail',
        items: [
            { productId: 'PROD-001', quantity: 50, price: 20 },
            { productId: 'PROD-003', quantity: 150, price: 25 },
        ],
    },
    {
        id: 'ORD-004',
        distributorName: 'Modern Traders',
        date: '2024-08-10',
        amount: 112000,
        status: 'Fulfilled',
        appliedPromotionId: 'PROMO-001',
        orderType: 'Retail',
        items: [
            { productId: 'PROD-001', quantity: 1000, price: 20 },
            { productId: 'PROD-002', quantity: 500, price: 35 },
            { productId: 'PROD-004', quantity: 200, price: 35 },
        ],
    },
    {
        id: 'ORD-005',
        distributorName: 'Gupta Distributors',
        date: '2024-08-09',
        amount: 32000,
        status: 'Cancelled',
        orderType: 'Retail',
        items: [
            { productId: 'PROD-001', quantity: 1000, price: 20 },
            { productId: 'PROD-005', quantity: 200, price: 22 },
        ],
    },
    {
        id: 'ORD-006',
        distributorName: 'Southern Wholesalers',
        date: '2024-08-08',
        amount: 56000,
        status: 'Fulfilled',
        orderType: 'Retail',
        items: [
            { productId: 'PROD-002', quantity: 400, price: 35 },
        ],
    },
    {
        id: 'ORD-PO-001',
        distributorName: 'Gupta Distributors',
        date: '2024-08-15',
        amount: 500000,
        status: 'Pending',
        orderType: 'Purchase',
        items: [
            { productId: 'PROD-001', quantity: 10000, price: 20 },
            { productId: 'PROD-002', quantity: 5000, price: 35 },
        ],
    },
];

export const sentNotifications: SentNotification[] = [
    {
        id: 'NOTIF-001',
        distributorName: 'Gupta Distributors',
        promotionName: 'Monsoon Bonanza',
        subject: 'New Promotion for You: Monsoon Bonanza!',
        body: 'Dear Gupta Distributors, get ready for the Monsoon Bonanza! Buy 6 Cool Cola 300ml and get 1 absolutely free. Offer valid from July 1 to Aug 31.',
        sentDate: '2024-07-01',
    },
    {
        id: 'NOTIF-002',
        distributorName: 'Modern Traders',
        promotionName: 'Monsoon Bonanza',
        subject: 'New Promotion for You: Monsoon Bonanza!',
        body: 'Dear Modern Traders, get ready for the Monsoon Bonanza! Buy 6 Cool Cola 300ml and get 1 absolutely free. Offer valid from July 1 to Aug 31.',
        sentDate: '2024-07-01',
    },
    {
        id: 'NOTIF-003',
        distributorName: 'Patel Trading Co.',
        promotionName: 'Independence Day Special',
        subject: 'Get ready for our Independence Day Special!',
        body: 'Dear Patel Trading Co., celebrate with our Independence Day Special! Offer a bundle of Cool Cola 500ml and Zesty Orange 500ml for just ₹65. Offer valid from Aug 10 to Aug 20.',
        sentDate: '2024-08-09',
    },
];

export const initialBudgets: Budget[] = [
    { id: 'BUD-001', name: 'Q3 North Region Beverage Budget', period: 'Q3 2024', totalAmount: 500000, allocatedAmount: 150000, spentAmount: 75000, targetIds: ['HIER-R1', 'CAT-1'], promotionTypes: ['Discount', 'Quantity-Based Freebie (Buy X, Get Y)'] },
    { id: 'BUD-002', name: 'Annual Maharashtra Budget', period: '2024', totalAmount: 2000000, allocatedAmount: 800000, spentAmount: 650000, targetIds: ['HIER-S3'], promotionTypes: [] },
    { id: 'BUD-003', name: 'Diwali Dhamaka Campaign', period: 'Q4 2024', totalAmount: 1000000, allocatedAmount: 0, spentAmount: 0, targetIds: [], promotionTypes: ['Contest'] },
    { id: 'BUD-004', name: 'Delhi Marketing Budget', period: 'Q3 2024', totalAmount: 100000, allocatedAmount: 0, spentAmount: 0, targetIds: ['HIER-S1'], parentId: 'BUD-001', promotionTypes: [] },
];

export const externalFactors: ExternalFactor[] = [
    {
        id: 'EF-001',
        name: 'North India Heatwave',
        type: 'Seasonality',
        description: 'An extended period of unusually high temperatures across the North region, leading to increased demand for beverages.',
        startDate: '2024-05-15',
        endDate: '2024-06-30',
        applicableHierarchyIds: ['HIER-R1'],
    },
    {
        id: 'EF-002',
        name: 'Competitor "FizzUp" Summer Campaign',
        type: 'CompetitorActivity',
        description: 'FizzUp is running a national buy-one-get-one-free campaign on all their 500ml SKUs.',
        startDate: '2024-05-01',
        endDate: '2024-06-30',
        applicableHierarchyIds: ['HIER-R1', 'HIER-R2'],
    },
    {
        id: 'EF-003',
        name: 'Diwali Festival Period',
        type: 'LocalEvent',
        description: 'The national Diwali festival period, which sees a significant increase in consumer spending and gifting.',
        startDate: '2024-10-25',
        endDate: '2024-11-05',
        applicableHierarchyIds: ['HIER-R1', 'HIER-R2'],
    }
];
